# Generated by Django 2.2 on 2023-03-04 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_too_tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dir',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dirs', to='db_too_tree.Dir'),
        ),
    ]
